AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: "lambda-sam-playwright"
  BucketName:
    Type: String
    Default: "lambda-sam-playwright-input-bucket"
  CreatedBy:
    Type: String
    Default: "sam-cli"
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg
  SlackToken:
    Type: String
    Default: ""
  SlackNoSend:
    Type: String
    Default: ""

# https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs22.x
    Tracing: Active
    Timeout: 3
    Architectures:
      - arm64
    CodeUri: ./
    Handler: index.handler
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        NODE_OPTIONS: --enable-source-maps
        ENV: !Ref Env
    Tags:
      Project: !Ref ProjectName
      CreatedBy: !Ref CreatedBy
  Api:
    TracingEnabled: true
    # Stageの生成を無効化するために設定、OpenAPIは使用していない: https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-resource-api.html#sam-api-openapiversion
    OpenApiVersion: 3.0.2

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # ---- ApiHealth Check Function start ----
  ApiHealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-health"
      Description: Health check function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/health
            Method: GET
    Metadata:
      BuildMethod: makefile
  ApiHealthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiHealthFunction}
      RetentionInDays: 90
  # ---- ApiHealth Check Function end ----

  # ---- ApiV1Snapshot Function start ----
  ApiV1SnapshotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-v1-snapshot"
      Description: V1 snapshot function
      Environment:
        Variables:
          PLAYWRIGHT_RUNNER_FUNCTION_NAME: !Sub "${ProjectName}-${Env}-playwright-runner"
      Events:
        Api:
          Type: Api
          Properties:
            Path: /api/v1/snapshot
            Method: POST
    Metadata:
      BuildMethod: makefile
  ApiV1SnapshotFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${ApiV1SnapshotFunction}
      RetentionInDays: 90
  # ---- ApiV1Snapshot Check Function end ----

  # ---- Slack Notification Function start ----
  SlackNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-slack-notification"
      Description: Slack notification function
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_NO_SEND: !Ref SlackNoSend
      Events:
        Api:
          Type: Api
          Properties:
            Path: /slack-notification
            Method: GET
    Metadata:
      BuildMethod: makefile
  SlackNotificationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SlackNotificationFunction}
      RetentionInDays: 90
  # ---- Slack Notification Function end ----

  # ---- Playwright Runner Function start ----
  PlaywrightRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Env}-playwright-runner"
      Description: Playwright runner function
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/containers/playwright-runner/
      DockerTag: 1.0.0
  PlaywrightRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PlaywrightRunnerFunction}
      RetentionInDays: 90
  # ---- Playwright Runner Function end ----

  S3InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
