AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: "lambda-sam-playwright"
  BucketName:
    Type: String
    Default: "lambda-sam-playwright-input-bucket"
  CreatedBy:
    Type: String
    Default: "sam-cli"
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg

# https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs22.x
    Tracing: Active
    Timeout: 3
    Architectures:
      - arm64
    CodeUri: ./
    Handler: index.handler
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        ENV: !Ref Env
    Tags:
      Project: !Ref ProjectName
      CreatedBy: !Ref CreatedBy
  Api:
    TracingEnabled: true

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-health"
      Description: Health check function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /health
            Method: GET
    Metadata:
      BuildMethod: makefile

  # ロググループは自動作成されないため、全ての関数に対応するロググループを手動で作成する
  HealthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HealthFunction}
      RetentionInDays: 90

  S3InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
