AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

# ESBuildを使ってビルドするための共通設定
# https://docs.aws.amazon.com/serverless-application-model/latest/developerguide/serverless-sam-cli-using-build-typescript.html
Metadata: &EsbuildSharedMetadata
  BuildMethod: esbuild
  BuildProperties: &EsbuildSharedBuildProperties
    Format: esm
    Minify: false
    Target: es2022
    OutExtension:
      - .js=.mjs
    Sourcemap: true

Parameters:
  ProjectName:
    Type: String
    Default: "lambda-sam-playwright"
  BucketName:
    Type: String
    Default: "lambda-sam-playwright-input-bucket"
  CreatedBy:
    Type: String
    Default: "sam-cli"
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg

Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs22.x
    Tracing: Active
    Architectures:
      - arm64
    CodeUri: ./
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        ENV: !Ref Env
    Tags:
      Project: !Ref ProjectName
      CreatedBy: !Ref CreatedBy
  Api:
    TracingEnabled: true

# Resources declares the AWS resources that you want to include in the stack
# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  S3InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName

  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-health"
      Handler: index.handler
      Timeout: 10
      Description: Health check function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /health
            Method: GET
    Metadata:
      <<: *EsbuildSharedMetadata
      BuildProperties:
        <<: *EsbuildSharedBuildProperties
        EntryPoints:
          - ./src/functions/health/index.ts

  # ロググループは自動作成されないため、全ての関数に対応するロググループを手動で作成する
  HealthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HealthFunction}
      RetentionInDays: 90
