AWSTemplateFormatVersion: 2010-09-09
Description: >-
  sam-app
Transform:
  - AWS::Serverless-2016-10-31

Parameters:
  ProjectName:
    Type: String
    Default: "lambda-sam-playwright"
  BucketName:
    Type: String
    Default: "lambda-sam-playwright-input-bucket"
  CreatedBy:
    Type: String
    Default: "sam-cli"
  Env:
    Type: String
    AllowedValues:
      - prd
      - stg
  SlackToken:
    Type: String
  SLACK_NO_SEND:
    Type: String

# https://docs.aws.amazon.com/ja_jp/serverless-application-model/latest/developerguide/sam-specification-template-anatomy-globals.html
Globals:
  Function:
    MemorySize: 128
    Runtime: nodejs22.x
    Tracing: Active
    Timeout: 3
    Architectures:
      - arm64
    CodeUri: ./
    Handler: index.handler
    LoggingConfig:
      LogFormat: JSON
    Environment:
      Variables:
        ENV: !Ref Env
    Tags:
      Project: !Ref ProjectName
      CreatedBy: !Ref CreatedBy
  Api:
    TracingEnabled: true

# https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/resources-section-structure.html
Resources:
  # ---- Health Check Function start ----
  HealthFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-health"
      Description: Health check function
      Events:
        Api:
          Type: Api
          Properties:
            Path: /health
            Method: GET
    Metadata:
      BuildMethod: makefile
  HealthFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${HealthFunction}
      RetentionInDays: 90
  # ---- Health Check Function end ----

  # ---- Slack Notification Function start ----
  SlackNotificationFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-slack-notification"
      Description: Slack notification function
      Environment:
        Variables:
          SLACK_TOKEN: !Ref SlackToken
          SLACK_NO_SEND: !Ref SLACK_NO_SEND
      Events:
        Api:
          Type: Api
          Properties:
            Path: /slack-notification
            Method: GET
    Metadata:
      BuildMethod: makefile
  SlackNotificationFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${SlackNotificationFunction}
      RetentionInDays: 90
  # ---- Slack Notification Function end ----

  # ---- Playwright Runner Function start ----
  PlaywrightRunnerFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Sub "${ProjectName}-${Environment}-playwright-runner"
      Description: Playwright runner function
      PackageType: Image
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src/containers/playwright-runner/
      DockerTag: 1.0.0
  PlaywrightRunnerFunctionLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: !Sub /aws/lambda/${PlaywrightRunnerFunction}
      RetentionInDays: 90
  # ---- Playwright Runner Function end ----

  S3InputBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
