name: CI

on:
  push:
    branches:
      - main
      - stg
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]

jobs:
  ci-app:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup
      - name: Run prettier
        run: pnpm lint:fmt
      - name: Run eslint
        run: pnpm lint:js
